Created IntakeSet command and Intake command group
bullbots/InfiniteRechargeJ pull request #42
Opened 2020-01-29 02:21 UTC by StephenDay1

2020-01-29 02:55 UTC, StephenDay1 commented
This is #25, sorry I forgot to put it in the title

2020-01-29 05:58 UTC, devinvs requested changes

2020-01-29 05:58 UTC, DevinVS commented on src/main/java/frc/robot/commands/Intake.java
> +}
I'm going to be honest, I didn't think about the naming conflicts here... For now, please delete this, I'm not sure we even need it, sorry.

2020-01-29 05:58 UTC, DevinVS commented on src/main/java/frc/robot/commands/IntakeSet.java
> +  boolean setIntake; // True = On, False = Off
This needs a better name, also change it in the constructor. My ideas right now are "state', "running", "isRunning", and "enabled",  but I'm pretty tired. We just need something that is a little more descriptive

2020-01-29 05:58 UTC, DevinVS commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public WPI_TalonSRX wheel_motor;
No. Since these are hardware devices, we need to keep these private. Also, why? You don't access these anywhere...

2020-02-04 01:55 UTC, devinvs requested changes

2020-02-04 01:55 UTC, DevinVS commented on src/main/java/frc/robot/commands/MoveDistance.java
> +    return Math.abs(currentPosition - targetDistance) == allowedError;
I believe you want <=

2020-02-07 01:08 UTC, devinvs requested changes

2020-02-07 01:08 UTC, DevinVS commented on src/main/java/frc/robot/commands/MoveDistance.java
> +    return Math.abs(currentPosition - targetDistance) >= allowedError;
This will return true if the error is greater than the allowed error... In other words, if the error is greater than the allowed, it will finish.

2020-02-12 01:31 UTC, devinvs approved these changes

2020-02-12 01:34 UTC, merged